# 基础镜像
FROM redis
# author
MAINTAINER codeonline

# 挂载目录
VOLUME /home/codeonline/redis
# 创建目录
RUN mkdir -p /home/codeonline/redis
# 指定路径
WORKDIR /home/codeonline/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/codeonline/redis/redis.conf
