#FROM openjdk:8-jdk
#LABEL maintainer=zhangcheng
#
#ENV PARAMS="--server.port=8080 --spring.profiles.active=prod --spring.cloud.nacos.discovery.server-addr=codeonline-nacos.codeonline-projects:8848 --spring.cloud.nacos.config.server-addr=codeonline-nacos.codeonline-projects:8848 --spring.cloud.nacos.config.namespace=prod --spring.cloud.nacos.config.file-extension=yml"
#RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
#
## 挂载目录
#VOLUME /home/ruoyi
## 创建目录
#RUN mkdir -p /home/ruoyi
## 指定路径
#WORKDIR /home/ruoyi
## 复制jar文件到路径
#COPY ./jar/codeonline-modules-cloud.jar /home/ruoyi/codeonline-modules-cloud.jar
#
#EXPOSE 8080
#
## 启动认证服务
#ENTRYPOINT ["/bin/sh","-c","java -Dfile.encoding=utf8 -Djava.security.egd=file:/dev/./urandom -jar codeonline-modules-cloud.jar ${PARAMS}"]

# 使用 openjdk:8-jdk 镜像作为基础镜像
FROM openjdk:8-jdk

# 添加Docker官方GPG密钥
RUN apt-get update \
    && apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl gnupg2 software-properties-common \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

# 安装Docker
RUN apt-get update \
    && apt-get install -y docker-ce docker-ce-cli containerd.io

LABEL maintainer=zhangcheng

ENV PARAMS="--server.port=8080 --spring.profiles.active=prod --spring.cloud.nacos.discovery.server-addr=codeonline-nacos.codeonline-projects:8848 --spring.cloud.nacos.config.server-addr=codeonline-nacos.codeonline-projects:8848 --spring.cloud.nacos.config.namespace=prod --spring.cloud.nacos.config.file-extension=yml"
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/codeonline-modules-cloud.jar /home/ruoyi/codeonline-modules-cloud.jar

EXPOSE 8080

# 启动认证服务
ENTRYPOINT ["/bin/sh","-c","java -Dfile.encoding=utf8 -Djava.security.egd=file:/dev/./urandom -jar codeonline-modules-cloud.jar ${PARAMS}"]
