/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The accessory of the artifact
 */
@ApiModel(description = "The accessory of the artifact")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class Accessory {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("artifact_id")
  private Long artifactId = null;

  @SerializedName("subject_artifact_id")
  private Long subjectArtifactId = null;

  @SerializedName("size")
  private Long size = null;

  @SerializedName("digest")
  private String digest = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("icon")
  private String icon = null;

  @SerializedName("creation_time")
  private String creationTime = null;

  public Accessory id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the accessory
   * @return id
  **/
  @ApiModelProperty(value = "The ID of the accessory")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Accessory artifactId(Long artifactId) {
    this.artifactId = artifactId;
    return this;
  }

   /**
   * The artifact id of the accessory
   * @return artifactId
  **/
  @ApiModelProperty(value = "The artifact id of the accessory")
  public Long getArtifactId() {
    return artifactId;
  }

  public void setArtifactId(Long artifactId) {
    this.artifactId = artifactId;
  }

  public Accessory subjectArtifactId(Long subjectArtifactId) {
    this.subjectArtifactId = subjectArtifactId;
    return this;
  }

   /**
   * The subject artifact id of the accessory
   * @return subjectArtifactId
  **/
  @ApiModelProperty(value = "The subject artifact id of the accessory")
  public Long getSubjectArtifactId() {
    return subjectArtifactId;
  }

  public void setSubjectArtifactId(Long subjectArtifactId) {
    this.subjectArtifactId = subjectArtifactId;
  }

  public Accessory size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * The artifact size of the accessory
   * @return size
  **/
  @ApiModelProperty(value = "The artifact size of the accessory")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public Accessory digest(String digest) {
    this.digest = digest;
    return this;
  }

   /**
   * The artifact digest of the accessory
   * @return digest
  **/
  @ApiModelProperty(value = "The artifact digest of the accessory")
  public String getDigest() {
    return digest;
  }

  public void setDigest(String digest) {
    this.digest = digest;
  }

  public Accessory type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The artifact size of the accessory
   * @return type
  **/
  @ApiModelProperty(value = "The artifact size of the accessory")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Accessory icon(String icon) {
    this.icon = icon;
    return this;
  }

   /**
   * The icon of the accessory
   * @return icon
  **/
  @ApiModelProperty(value = "The icon of the accessory")
  public String getIcon() {
    return icon;
  }

  public void setIcon(String icon) {
    this.icon = icon;
  }

  public Accessory creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * The creation time of the accessory
   * @return creationTime
  **/
  @ApiModelProperty(value = "The creation time of the accessory")
  public String getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Accessory accessory = (Accessory) o;
    return Objects.equals(this.id, accessory.id) &&
        Objects.equals(this.artifactId, accessory.artifactId) &&
        Objects.equals(this.subjectArtifactId, accessory.subjectArtifactId) &&
        Objects.equals(this.size, accessory.size) &&
        Objects.equals(this.digest, accessory.digest) &&
        Objects.equals(this.type, accessory.type) &&
        Objects.equals(this.icon, accessory.icon) &&
        Objects.equals(this.creationTime, accessory.creationTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, artifactId, subjectArtifactId, size, digest, type, icon, creationTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Accessory {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    artifactId: ").append(toIndentedString(artifactId)).append("\n");
    sb.append("    subjectArtifactId: ").append(toIndentedString(subjectArtifactId)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

