/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ConfigurationsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class ConfigurationsResponse {
  @SerializedName("auth_mode")
  private StringConfigItem authMode = null;

  @SerializedName("ldap_base_dn")
  private StringConfigItem ldapBaseDn = null;

  @SerializedName("ldap_filter")
  private StringConfigItem ldapFilter = null;

  @SerializedName("ldap_group_base_dn")
  private StringConfigItem ldapGroupBaseDn = null;

  @SerializedName("ldap_group_admin_dn")
  private StringConfigItem ldapGroupAdminDn = null;

  @SerializedName("ldap_group_attribute_name")
  private StringConfigItem ldapGroupAttributeName = null;

  @SerializedName("ldap_group_search_filter")
  private StringConfigItem ldapGroupSearchFilter = null;

  @SerializedName("ldap_group_search_scope")
  private IntegerConfigItem ldapGroupSearchScope = null;

  @SerializedName("ldap_scope")
  private IntegerConfigItem ldapScope = null;

  @SerializedName("ldap_search_dn")
  private StringConfigItem ldapSearchDn = null;

  @SerializedName("ldap_timeout")
  private IntegerConfigItem ldapTimeout = null;

  @SerializedName("ldap_uid")
  private StringConfigItem ldapUid = null;

  @SerializedName("ldap_url")
  private StringConfigItem ldapUrl = null;

  @SerializedName("ldap_verify_cert")
  private BoolConfigItem ldapVerifyCert = null;

  @SerializedName("ldap_group_membership_attribute")
  private StringConfigItem ldapGroupMembershipAttribute = null;

  @SerializedName("project_creation_restriction")
  private StringConfigItem projectCreationRestriction = null;

  @SerializedName("read_only")
  private BoolConfigItem readOnly = null;

  @SerializedName("self_registration")
  private BoolConfigItem selfRegistration = null;

  @SerializedName("token_expiration")
  private IntegerConfigItem tokenExpiration = null;

  @SerializedName("uaa_client_id")
  private StringConfigItem uaaClientId = null;

  @SerializedName("uaa_client_secret")
  private StringConfigItem uaaClientSecret = null;

  @SerializedName("uaa_endpoint")
  private StringConfigItem uaaEndpoint = null;

  @SerializedName("uaa_verify_cert")
  private BoolConfigItem uaaVerifyCert = null;

  @SerializedName("http_authproxy_endpoint")
  private StringConfigItem httpAuthproxyEndpoint = null;

  @SerializedName("http_authproxy_tokenreview_endpoint")
  private StringConfigItem httpAuthproxyTokenreviewEndpoint = null;

  @SerializedName("http_authproxy_admin_groups")
  private StringConfigItem httpAuthproxyAdminGroups = null;

  @SerializedName("http_authproxy_admin_usernames")
  private StringConfigItem httpAuthproxyAdminUsernames = null;

  @SerializedName("http_authproxy_verify_cert")
  private BoolConfigItem httpAuthproxyVerifyCert = null;

  @SerializedName("http_authproxy_skip_search")
  private BoolConfigItem httpAuthproxySkipSearch = null;

  @SerializedName("http_authproxy_server_certificate")
  private StringConfigItem httpAuthproxyServerCertificate = null;

  @SerializedName("oidc_name")
  private StringConfigItem oidcName = null;

  @SerializedName("oidc_endpoint")
  private StringConfigItem oidcEndpoint = null;

  @SerializedName("oidc_client_id")
  private StringConfigItem oidcClientId = null;

  @SerializedName("oidc_groups_claim")
  private StringConfigItem oidcGroupsClaim = null;

  @SerializedName("oidc_admin_group")
  private StringConfigItem oidcAdminGroup = null;

  @SerializedName("oidc_group_filter")
  private StringConfigItem oidcGroupFilter = null;

  @SerializedName("oidc_scope")
  private StringConfigItem oidcScope = null;

  @SerializedName("oidc_user_claim")
  private StringConfigItem oidcUserClaim = null;

  @SerializedName("oidc_verify_cert")
  private BoolConfigItem oidcVerifyCert = null;

  @SerializedName("oidc_auto_onboard")
  private BoolConfigItem oidcAutoOnboard = null;

  @SerializedName("oidc_extra_redirect_parms")
  private StringConfigItem oidcExtraRedirectParms = null;

  @SerializedName("robot_token_duration")
  private IntegerConfigItem robotTokenDuration = null;

  @SerializedName("robot_name_prefix")
  private StringConfigItem robotNamePrefix = null;

  @SerializedName("notification_enable")
  private BoolConfigItem notificationEnable = null;

  @SerializedName("quota_per_project_enable")
  private BoolConfigItem quotaPerProjectEnable = null;

  @SerializedName("storage_per_project")
  private IntegerConfigItem storagePerProject = null;

  @SerializedName("audit_log_forward_endpoint")
  private StringConfigItem auditLogForwardEndpoint = null;

  @SerializedName("skip_audit_log_database")
  private BoolConfigItem skipAuditLogDatabase = null;

  @SerializedName("scan_all_policy")
  private ConfigurationsResponseScanAllPolicy scanAllPolicy = null;

  @SerializedName("session_timeout")
  private IntegerConfigItem sessionTimeout = null;

  public ConfigurationsResponse authMode(StringConfigItem authMode) {
    this.authMode = authMode;
    return this;
  }

   /**
   * The auth mode of current system, such as \&quot;db_auth\&quot;, \&quot;ldap_auth\&quot;, \&quot;oidc_auth\&quot;
   * @return authMode
  **/
  @ApiModelProperty(value = "The auth mode of current system, such as \"db_auth\", \"ldap_auth\", \"oidc_auth\"")
  public StringConfigItem getAuthMode() {
    return authMode;
  }

  public void setAuthMode(StringConfigItem authMode) {
    this.authMode = authMode;
  }

  public ConfigurationsResponse ldapBaseDn(StringConfigItem ldapBaseDn) {
    this.ldapBaseDn = ldapBaseDn;
    return this;
  }

   /**
   * The Base DN for LDAP binding.
   * @return ldapBaseDn
  **/
  @ApiModelProperty(value = "The Base DN for LDAP binding.")
  public StringConfigItem getLdapBaseDn() {
    return ldapBaseDn;
  }

  public void setLdapBaseDn(StringConfigItem ldapBaseDn) {
    this.ldapBaseDn = ldapBaseDn;
  }

  public ConfigurationsResponse ldapFilter(StringConfigItem ldapFilter) {
    this.ldapFilter = ldapFilter;
    return this;
  }

   /**
   * The filter for LDAP search
   * @return ldapFilter
  **/
  @ApiModelProperty(value = "The filter for LDAP search")
  public StringConfigItem getLdapFilter() {
    return ldapFilter;
  }

  public void setLdapFilter(StringConfigItem ldapFilter) {
    this.ldapFilter = ldapFilter;
  }

  public ConfigurationsResponse ldapGroupBaseDn(StringConfigItem ldapGroupBaseDn) {
    this.ldapGroupBaseDn = ldapGroupBaseDn;
    return this;
  }

   /**
   * The base DN to search LDAP group.
   * @return ldapGroupBaseDn
  **/
  @ApiModelProperty(value = "The base DN to search LDAP group.")
  public StringConfigItem getLdapGroupBaseDn() {
    return ldapGroupBaseDn;
  }

  public void setLdapGroupBaseDn(StringConfigItem ldapGroupBaseDn) {
    this.ldapGroupBaseDn = ldapGroupBaseDn;
  }

  public ConfigurationsResponse ldapGroupAdminDn(StringConfigItem ldapGroupAdminDn) {
    this.ldapGroupAdminDn = ldapGroupAdminDn;
    return this;
  }

   /**
   * Specify the ldap group which have the same privilege with Harbor admin
   * @return ldapGroupAdminDn
  **/
  @ApiModelProperty(value = "Specify the ldap group which have the same privilege with Harbor admin")
  public StringConfigItem getLdapGroupAdminDn() {
    return ldapGroupAdminDn;
  }

  public void setLdapGroupAdminDn(StringConfigItem ldapGroupAdminDn) {
    this.ldapGroupAdminDn = ldapGroupAdminDn;
  }

  public ConfigurationsResponse ldapGroupAttributeName(StringConfigItem ldapGroupAttributeName) {
    this.ldapGroupAttributeName = ldapGroupAttributeName;
    return this;
  }

   /**
   * The attribute which is used as identity of the LDAP group, default is cn.&#39;
   * @return ldapGroupAttributeName
  **/
  @ApiModelProperty(value = "The attribute which is used as identity of the LDAP group, default is cn.'")
  public StringConfigItem getLdapGroupAttributeName() {
    return ldapGroupAttributeName;
  }

  public void setLdapGroupAttributeName(StringConfigItem ldapGroupAttributeName) {
    this.ldapGroupAttributeName = ldapGroupAttributeName;
  }

  public ConfigurationsResponse ldapGroupSearchFilter(StringConfigItem ldapGroupSearchFilter) {
    this.ldapGroupSearchFilter = ldapGroupSearchFilter;
    return this;
  }

   /**
   * The filter to search the ldap group
   * @return ldapGroupSearchFilter
  **/
  @ApiModelProperty(value = "The filter to search the ldap group")
  public StringConfigItem getLdapGroupSearchFilter() {
    return ldapGroupSearchFilter;
  }

  public void setLdapGroupSearchFilter(StringConfigItem ldapGroupSearchFilter) {
    this.ldapGroupSearchFilter = ldapGroupSearchFilter;
  }

  public ConfigurationsResponse ldapGroupSearchScope(IntegerConfigItem ldapGroupSearchScope) {
    this.ldapGroupSearchScope = ldapGroupSearchScope;
    return this;
  }

   /**
   * The scope to search ldap group. &#39;&#39;0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE&#39;&#39;
   * @return ldapGroupSearchScope
  **/
  @ApiModelProperty(value = "The scope to search ldap group. ''0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE''")
  public IntegerConfigItem getLdapGroupSearchScope() {
    return ldapGroupSearchScope;
  }

  public void setLdapGroupSearchScope(IntegerConfigItem ldapGroupSearchScope) {
    this.ldapGroupSearchScope = ldapGroupSearchScope;
  }

  public ConfigurationsResponse ldapScope(IntegerConfigItem ldapScope) {
    this.ldapScope = ldapScope;
    return this;
  }

   /**
   * The scope to search ldap users,&#39;0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE&#39;
   * @return ldapScope
  **/
  @ApiModelProperty(value = "The scope to search ldap users,'0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE'")
  public IntegerConfigItem getLdapScope() {
    return ldapScope;
  }

  public void setLdapScope(IntegerConfigItem ldapScope) {
    this.ldapScope = ldapScope;
  }

  public ConfigurationsResponse ldapSearchDn(StringConfigItem ldapSearchDn) {
    this.ldapSearchDn = ldapSearchDn;
    return this;
  }

   /**
   * The DN of the user to do the search.
   * @return ldapSearchDn
  **/
  @ApiModelProperty(value = "The DN of the user to do the search.")
  public StringConfigItem getLdapSearchDn() {
    return ldapSearchDn;
  }

  public void setLdapSearchDn(StringConfigItem ldapSearchDn) {
    this.ldapSearchDn = ldapSearchDn;
  }

  public ConfigurationsResponse ldapTimeout(IntegerConfigItem ldapTimeout) {
    this.ldapTimeout = ldapTimeout;
    return this;
  }

   /**
   * Timeout in seconds for connection to LDAP server
   * @return ldapTimeout
  **/
  @ApiModelProperty(value = "Timeout in seconds for connection to LDAP server")
  public IntegerConfigItem getLdapTimeout() {
    return ldapTimeout;
  }

  public void setLdapTimeout(IntegerConfigItem ldapTimeout) {
    this.ldapTimeout = ldapTimeout;
  }

  public ConfigurationsResponse ldapUid(StringConfigItem ldapUid) {
    this.ldapUid = ldapUid;
    return this;
  }

   /**
   * The attribute which is used as identity for the LDAP binding, such as \&quot;CN\&quot; or \&quot;SAMAccountname\&quot;
   * @return ldapUid
  **/
  @ApiModelProperty(value = "The attribute which is used as identity for the LDAP binding, such as \"CN\" or \"SAMAccountname\"")
  public StringConfigItem getLdapUid() {
    return ldapUid;
  }

  public void setLdapUid(StringConfigItem ldapUid) {
    this.ldapUid = ldapUid;
  }

  public ConfigurationsResponse ldapUrl(StringConfigItem ldapUrl) {
    this.ldapUrl = ldapUrl;
    return this;
  }

   /**
   * The URL of LDAP server
   * @return ldapUrl
  **/
  @ApiModelProperty(value = "The URL of LDAP server")
  public StringConfigItem getLdapUrl() {
    return ldapUrl;
  }

  public void setLdapUrl(StringConfigItem ldapUrl) {
    this.ldapUrl = ldapUrl;
  }

  public ConfigurationsResponse ldapVerifyCert(BoolConfigItem ldapVerifyCert) {
    this.ldapVerifyCert = ldapVerifyCert;
    return this;
  }

   /**
   * Whether verify your OIDC server certificate, disable it if your OIDC server is hosted via self-hosted certificate.
   * @return ldapVerifyCert
  **/
  @ApiModelProperty(value = "Whether verify your OIDC server certificate, disable it if your OIDC server is hosted via self-hosted certificate.")
  public BoolConfigItem getLdapVerifyCert() {
    return ldapVerifyCert;
  }

  public void setLdapVerifyCert(BoolConfigItem ldapVerifyCert) {
    this.ldapVerifyCert = ldapVerifyCert;
  }

  public ConfigurationsResponse ldapGroupMembershipAttribute(StringConfigItem ldapGroupMembershipAttribute) {
    this.ldapGroupMembershipAttribute = ldapGroupMembershipAttribute;
    return this;
  }

   /**
   * The user attribute to identify the group membership
   * @return ldapGroupMembershipAttribute
  **/
  @ApiModelProperty(value = "The user attribute to identify the group membership")
  public StringConfigItem getLdapGroupMembershipAttribute() {
    return ldapGroupMembershipAttribute;
  }

  public void setLdapGroupMembershipAttribute(StringConfigItem ldapGroupMembershipAttribute) {
    this.ldapGroupMembershipAttribute = ldapGroupMembershipAttribute;
  }

  public ConfigurationsResponse projectCreationRestriction(StringConfigItem projectCreationRestriction) {
    this.projectCreationRestriction = projectCreationRestriction;
    return this;
  }

   /**
   * Indicate who can create projects, it could be &#39;&#39;adminonly&#39;&#39; or &#39;&#39;everyone&#39;&#39;.
   * @return projectCreationRestriction
  **/
  @ApiModelProperty(value = "Indicate who can create projects, it could be ''adminonly'' or ''everyone''.")
  public StringConfigItem getProjectCreationRestriction() {
    return projectCreationRestriction;
  }

  public void setProjectCreationRestriction(StringConfigItem projectCreationRestriction) {
    this.projectCreationRestriction = projectCreationRestriction;
  }

  public ConfigurationsResponse readOnly(BoolConfigItem readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * The flag to indicate whether Harbor is in readonly mode.
   * @return readOnly
  **/
  @ApiModelProperty(value = "The flag to indicate whether Harbor is in readonly mode.")
  public BoolConfigItem getReadOnly() {
    return readOnly;
  }

  public void setReadOnly(BoolConfigItem readOnly) {
    this.readOnly = readOnly;
  }

  public ConfigurationsResponse selfRegistration(BoolConfigItem selfRegistration) {
    this.selfRegistration = selfRegistration;
    return this;
  }

   /**
   * Whether the Harbor instance supports self-registration.  If it&#39;&#39;s set to false, admin need to add user to the instance.
   * @return selfRegistration
  **/
  @ApiModelProperty(value = "Whether the Harbor instance supports self-registration.  If it''s set to false, admin need to add user to the instance.")
  public BoolConfigItem getSelfRegistration() {
    return selfRegistration;
  }

  public void setSelfRegistration(BoolConfigItem selfRegistration) {
    this.selfRegistration = selfRegistration;
  }

  public ConfigurationsResponse tokenExpiration(IntegerConfigItem tokenExpiration) {
    this.tokenExpiration = tokenExpiration;
    return this;
  }

   /**
   * The expiration time of the token for internal Registry, in minutes.
   * @return tokenExpiration
  **/
  @ApiModelProperty(value = "The expiration time of the token for internal Registry, in minutes.")
  public IntegerConfigItem getTokenExpiration() {
    return tokenExpiration;
  }

  public void setTokenExpiration(IntegerConfigItem tokenExpiration) {
    this.tokenExpiration = tokenExpiration;
  }

  public ConfigurationsResponse uaaClientId(StringConfigItem uaaClientId) {
    this.uaaClientId = uaaClientId;
    return this;
  }

   /**
   * The client id of UAA
   * @return uaaClientId
  **/
  @ApiModelProperty(value = "The client id of UAA")
  public StringConfigItem getUaaClientId() {
    return uaaClientId;
  }

  public void setUaaClientId(StringConfigItem uaaClientId) {
    this.uaaClientId = uaaClientId;
  }

  public ConfigurationsResponse uaaClientSecret(StringConfigItem uaaClientSecret) {
    this.uaaClientSecret = uaaClientSecret;
    return this;
  }

   /**
   * The client secret of the UAA
   * @return uaaClientSecret
  **/
  @ApiModelProperty(value = "The client secret of the UAA")
  public StringConfigItem getUaaClientSecret() {
    return uaaClientSecret;
  }

  public void setUaaClientSecret(StringConfigItem uaaClientSecret) {
    this.uaaClientSecret = uaaClientSecret;
  }

  public ConfigurationsResponse uaaEndpoint(StringConfigItem uaaEndpoint) {
    this.uaaEndpoint = uaaEndpoint;
    return this;
  }

   /**
   * The endpoint of the UAA
   * @return uaaEndpoint
  **/
  @ApiModelProperty(value = "The endpoint of the UAA")
  public StringConfigItem getUaaEndpoint() {
    return uaaEndpoint;
  }

  public void setUaaEndpoint(StringConfigItem uaaEndpoint) {
    this.uaaEndpoint = uaaEndpoint;
  }

  public ConfigurationsResponse uaaVerifyCert(BoolConfigItem uaaVerifyCert) {
    this.uaaVerifyCert = uaaVerifyCert;
    return this;
  }

   /**
   * Verify the certificate in UAA server
   * @return uaaVerifyCert
  **/
  @ApiModelProperty(value = "Verify the certificate in UAA server")
  public BoolConfigItem getUaaVerifyCert() {
    return uaaVerifyCert;
  }

  public void setUaaVerifyCert(BoolConfigItem uaaVerifyCert) {
    this.uaaVerifyCert = uaaVerifyCert;
  }

  public ConfigurationsResponse httpAuthproxyEndpoint(StringConfigItem httpAuthproxyEndpoint) {
    this.httpAuthproxyEndpoint = httpAuthproxyEndpoint;
    return this;
  }

   /**
   * The endpoint of the HTTP auth
   * @return httpAuthproxyEndpoint
  **/
  @ApiModelProperty(value = "The endpoint of the HTTP auth")
  public StringConfigItem getHttpAuthproxyEndpoint() {
    return httpAuthproxyEndpoint;
  }

  public void setHttpAuthproxyEndpoint(StringConfigItem httpAuthproxyEndpoint) {
    this.httpAuthproxyEndpoint = httpAuthproxyEndpoint;
  }

  public ConfigurationsResponse httpAuthproxyTokenreviewEndpoint(StringConfigItem httpAuthproxyTokenreviewEndpoint) {
    this.httpAuthproxyTokenreviewEndpoint = httpAuthproxyTokenreviewEndpoint;
    return this;
  }

   /**
   * The token review endpoint
   * @return httpAuthproxyTokenreviewEndpoint
  **/
  @ApiModelProperty(value = "The token review endpoint")
  public StringConfigItem getHttpAuthproxyTokenreviewEndpoint() {
    return httpAuthproxyTokenreviewEndpoint;
  }

  public void setHttpAuthproxyTokenreviewEndpoint(StringConfigItem httpAuthproxyTokenreviewEndpoint) {
    this.httpAuthproxyTokenreviewEndpoint = httpAuthproxyTokenreviewEndpoint;
  }

  public ConfigurationsResponse httpAuthproxyAdminGroups(StringConfigItem httpAuthproxyAdminGroups) {
    this.httpAuthproxyAdminGroups = httpAuthproxyAdminGroups;
    return this;
  }

   /**
   * The group which has the harbor admin privileges
   * @return httpAuthproxyAdminGroups
  **/
  @ApiModelProperty(value = "The group which has the harbor admin privileges")
  public StringConfigItem getHttpAuthproxyAdminGroups() {
    return httpAuthproxyAdminGroups;
  }

  public void setHttpAuthproxyAdminGroups(StringConfigItem httpAuthproxyAdminGroups) {
    this.httpAuthproxyAdminGroups = httpAuthproxyAdminGroups;
  }

  public ConfigurationsResponse httpAuthproxyAdminUsernames(StringConfigItem httpAuthproxyAdminUsernames) {
    this.httpAuthproxyAdminUsernames = httpAuthproxyAdminUsernames;
    return this;
  }

   /**
   * The usernames which has the harbor admin privileges
   * @return httpAuthproxyAdminUsernames
  **/
  @ApiModelProperty(value = "The usernames which has the harbor admin privileges")
  public StringConfigItem getHttpAuthproxyAdminUsernames() {
    return httpAuthproxyAdminUsernames;
  }

  public void setHttpAuthproxyAdminUsernames(StringConfigItem httpAuthproxyAdminUsernames) {
    this.httpAuthproxyAdminUsernames = httpAuthproxyAdminUsernames;
  }

  public ConfigurationsResponse httpAuthproxyVerifyCert(BoolConfigItem httpAuthproxyVerifyCert) {
    this.httpAuthproxyVerifyCert = httpAuthproxyVerifyCert;
    return this;
  }

   /**
   * Verify the HTTP auth provider&#39;s certificate
   * @return httpAuthproxyVerifyCert
  **/
  @ApiModelProperty(value = "Verify the HTTP auth provider's certificate")
  public BoolConfigItem getHttpAuthproxyVerifyCert() {
    return httpAuthproxyVerifyCert;
  }

  public void setHttpAuthproxyVerifyCert(BoolConfigItem httpAuthproxyVerifyCert) {
    this.httpAuthproxyVerifyCert = httpAuthproxyVerifyCert;
  }

  public ConfigurationsResponse httpAuthproxySkipSearch(BoolConfigItem httpAuthproxySkipSearch) {
    this.httpAuthproxySkipSearch = httpAuthproxySkipSearch;
    return this;
  }

   /**
   * Search user before onboard
   * @return httpAuthproxySkipSearch
  **/
  @ApiModelProperty(value = "Search user before onboard")
  public BoolConfigItem getHttpAuthproxySkipSearch() {
    return httpAuthproxySkipSearch;
  }

  public void setHttpAuthproxySkipSearch(BoolConfigItem httpAuthproxySkipSearch) {
    this.httpAuthproxySkipSearch = httpAuthproxySkipSearch;
  }

  public ConfigurationsResponse httpAuthproxyServerCertificate(StringConfigItem httpAuthproxyServerCertificate) {
    this.httpAuthproxyServerCertificate = httpAuthproxyServerCertificate;
    return this;
  }

   /**
   * The certificate of the HTTP auth provider
   * @return httpAuthproxyServerCertificate
  **/
  @ApiModelProperty(value = "The certificate of the HTTP auth provider")
  public StringConfigItem getHttpAuthproxyServerCertificate() {
    return httpAuthproxyServerCertificate;
  }

  public void setHttpAuthproxyServerCertificate(StringConfigItem httpAuthproxyServerCertificate) {
    this.httpAuthproxyServerCertificate = httpAuthproxyServerCertificate;
  }

  public ConfigurationsResponse oidcName(StringConfigItem oidcName) {
    this.oidcName = oidcName;
    return this;
  }

   /**
   * The OIDC provider name
   * @return oidcName
  **/
  @ApiModelProperty(value = "The OIDC provider name")
  public StringConfigItem getOidcName() {
    return oidcName;
  }

  public void setOidcName(StringConfigItem oidcName) {
    this.oidcName = oidcName;
  }

  public ConfigurationsResponse oidcEndpoint(StringConfigItem oidcEndpoint) {
    this.oidcEndpoint = oidcEndpoint;
    return this;
  }

   /**
   * The endpoint of the OIDC provider
   * @return oidcEndpoint
  **/
  @ApiModelProperty(value = "The endpoint of the OIDC provider")
  public StringConfigItem getOidcEndpoint() {
    return oidcEndpoint;
  }

  public void setOidcEndpoint(StringConfigItem oidcEndpoint) {
    this.oidcEndpoint = oidcEndpoint;
  }

  public ConfigurationsResponse oidcClientId(StringConfigItem oidcClientId) {
    this.oidcClientId = oidcClientId;
    return this;
  }

   /**
   * The client ID of the OIDC provider
   * @return oidcClientId
  **/
  @ApiModelProperty(value = "The client ID of the OIDC provider")
  public StringConfigItem getOidcClientId() {
    return oidcClientId;
  }

  public void setOidcClientId(StringConfigItem oidcClientId) {
    this.oidcClientId = oidcClientId;
  }

  public ConfigurationsResponse oidcGroupsClaim(StringConfigItem oidcGroupsClaim) {
    this.oidcGroupsClaim = oidcGroupsClaim;
    return this;
  }

   /**
   * The attribute claims the group name
   * @return oidcGroupsClaim
  **/
  @ApiModelProperty(value = "The attribute claims the group name")
  public StringConfigItem getOidcGroupsClaim() {
    return oidcGroupsClaim;
  }

  public void setOidcGroupsClaim(StringConfigItem oidcGroupsClaim) {
    this.oidcGroupsClaim = oidcGroupsClaim;
  }

  public ConfigurationsResponse oidcAdminGroup(StringConfigItem oidcAdminGroup) {
    this.oidcAdminGroup = oidcAdminGroup;
    return this;
  }

   /**
   * The OIDC group which has the harbor admin privileges
   * @return oidcAdminGroup
  **/
  @ApiModelProperty(value = "The OIDC group which has the harbor admin privileges")
  public StringConfigItem getOidcAdminGroup() {
    return oidcAdminGroup;
  }

  public void setOidcAdminGroup(StringConfigItem oidcAdminGroup) {
    this.oidcAdminGroup = oidcAdminGroup;
  }

  public ConfigurationsResponse oidcGroupFilter(StringConfigItem oidcGroupFilter) {
    this.oidcGroupFilter = oidcGroupFilter;
    return this;
  }

   /**
   * The OIDC group filter which filters out the group doesn&#39;t match the regular expression
   * @return oidcGroupFilter
  **/
  @ApiModelProperty(value = "The OIDC group filter which filters out the group doesn't match the regular expression")
  public StringConfigItem getOidcGroupFilter() {
    return oidcGroupFilter;
  }

  public void setOidcGroupFilter(StringConfigItem oidcGroupFilter) {
    this.oidcGroupFilter = oidcGroupFilter;
  }

  public ConfigurationsResponse oidcScope(StringConfigItem oidcScope) {
    this.oidcScope = oidcScope;
    return this;
  }

   /**
   * The scope of the OIDC provider
   * @return oidcScope
  **/
  @ApiModelProperty(value = "The scope of the OIDC provider")
  public StringConfigItem getOidcScope() {
    return oidcScope;
  }

  public void setOidcScope(StringConfigItem oidcScope) {
    this.oidcScope = oidcScope;
  }

  public ConfigurationsResponse oidcUserClaim(StringConfigItem oidcUserClaim) {
    this.oidcUserClaim = oidcUserClaim;
    return this;
  }

   /**
   * The attribute claims the username
   * @return oidcUserClaim
  **/
  @ApiModelProperty(value = "The attribute claims the username")
  public StringConfigItem getOidcUserClaim() {
    return oidcUserClaim;
  }

  public void setOidcUserClaim(StringConfigItem oidcUserClaim) {
    this.oidcUserClaim = oidcUserClaim;
  }

  public ConfigurationsResponse oidcVerifyCert(BoolConfigItem oidcVerifyCert) {
    this.oidcVerifyCert = oidcVerifyCert;
    return this;
  }

   /**
   * Verify the OIDC provider&#39;s certificate&#39;
   * @return oidcVerifyCert
  **/
  @ApiModelProperty(value = "Verify the OIDC provider's certificate'")
  public BoolConfigItem getOidcVerifyCert() {
    return oidcVerifyCert;
  }

  public void setOidcVerifyCert(BoolConfigItem oidcVerifyCert) {
    this.oidcVerifyCert = oidcVerifyCert;
  }

  public ConfigurationsResponse oidcAutoOnboard(BoolConfigItem oidcAutoOnboard) {
    this.oidcAutoOnboard = oidcAutoOnboard;
    return this;
  }

   /**
   * Auto onboard the OIDC user
   * @return oidcAutoOnboard
  **/
  @ApiModelProperty(value = "Auto onboard the OIDC user")
  public BoolConfigItem getOidcAutoOnboard() {
    return oidcAutoOnboard;
  }

  public void setOidcAutoOnboard(BoolConfigItem oidcAutoOnboard) {
    this.oidcAutoOnboard = oidcAutoOnboard;
  }

  public ConfigurationsResponse oidcExtraRedirectParms(StringConfigItem oidcExtraRedirectParms) {
    this.oidcExtraRedirectParms = oidcExtraRedirectParms;
    return this;
  }

   /**
   * Extra parameters to add when redirect request to OIDC provider
   * @return oidcExtraRedirectParms
  **/
  @ApiModelProperty(value = "Extra parameters to add when redirect request to OIDC provider")
  public StringConfigItem getOidcExtraRedirectParms() {
    return oidcExtraRedirectParms;
  }

  public void setOidcExtraRedirectParms(StringConfigItem oidcExtraRedirectParms) {
    this.oidcExtraRedirectParms = oidcExtraRedirectParms;
  }

  public ConfigurationsResponse robotTokenDuration(IntegerConfigItem robotTokenDuration) {
    this.robotTokenDuration = robotTokenDuration;
    return this;
  }

   /**
   * The robot account token duration in days
   * @return robotTokenDuration
  **/
  @ApiModelProperty(value = "The robot account token duration in days")
  public IntegerConfigItem getRobotTokenDuration() {
    return robotTokenDuration;
  }

  public void setRobotTokenDuration(IntegerConfigItem robotTokenDuration) {
    this.robotTokenDuration = robotTokenDuration;
  }

  public ConfigurationsResponse robotNamePrefix(StringConfigItem robotNamePrefix) {
    this.robotNamePrefix = robotNamePrefix;
    return this;
  }

   /**
   * The rebot account name prefix
   * @return robotNamePrefix
  **/
  @ApiModelProperty(value = "The rebot account name prefix")
  public StringConfigItem getRobotNamePrefix() {
    return robotNamePrefix;
  }

  public void setRobotNamePrefix(StringConfigItem robotNamePrefix) {
    this.robotNamePrefix = robotNamePrefix;
  }

  public ConfigurationsResponse notificationEnable(BoolConfigItem notificationEnable) {
    this.notificationEnable = notificationEnable;
    return this;
  }

   /**
   * Enable notification
   * @return notificationEnable
  **/
  @ApiModelProperty(value = "Enable notification")
  public BoolConfigItem getNotificationEnable() {
    return notificationEnable;
  }

  public void setNotificationEnable(BoolConfigItem notificationEnable) {
    this.notificationEnable = notificationEnable;
  }

  public ConfigurationsResponse quotaPerProjectEnable(BoolConfigItem quotaPerProjectEnable) {
    this.quotaPerProjectEnable = quotaPerProjectEnable;
    return this;
  }

   /**
   * Enable quota per project
   * @return quotaPerProjectEnable
  **/
  @ApiModelProperty(value = "Enable quota per project")
  public BoolConfigItem getQuotaPerProjectEnable() {
    return quotaPerProjectEnable;
  }

  public void setQuotaPerProjectEnable(BoolConfigItem quotaPerProjectEnable) {
    this.quotaPerProjectEnable = quotaPerProjectEnable;
  }

  public ConfigurationsResponse storagePerProject(IntegerConfigItem storagePerProject) {
    this.storagePerProject = storagePerProject;
    return this;
  }

   /**
   * The storage quota per project
   * @return storagePerProject
  **/
  @ApiModelProperty(value = "The storage quota per project")
  public IntegerConfigItem getStoragePerProject() {
    return storagePerProject;
  }

  public void setStoragePerProject(IntegerConfigItem storagePerProject) {
    this.storagePerProject = storagePerProject;
  }

  public ConfigurationsResponse auditLogForwardEndpoint(StringConfigItem auditLogForwardEndpoint) {
    this.auditLogForwardEndpoint = auditLogForwardEndpoint;
    return this;
  }

   /**
   * The endpoint of the audit log forwarder
   * @return auditLogForwardEndpoint
  **/
  @ApiModelProperty(value = "The endpoint of the audit log forwarder")
  public StringConfigItem getAuditLogForwardEndpoint() {
    return auditLogForwardEndpoint;
  }

  public void setAuditLogForwardEndpoint(StringConfigItem auditLogForwardEndpoint) {
    this.auditLogForwardEndpoint = auditLogForwardEndpoint;
  }

  public ConfigurationsResponse skipAuditLogDatabase(BoolConfigItem skipAuditLogDatabase) {
    this.skipAuditLogDatabase = skipAuditLogDatabase;
    return this;
  }

   /**
   * Whether skip the audit log in database
   * @return skipAuditLogDatabase
  **/
  @ApiModelProperty(value = "Whether skip the audit log in database")
  public BoolConfigItem getSkipAuditLogDatabase() {
    return skipAuditLogDatabase;
  }

  public void setSkipAuditLogDatabase(BoolConfigItem skipAuditLogDatabase) {
    this.skipAuditLogDatabase = skipAuditLogDatabase;
  }

  public ConfigurationsResponse scanAllPolicy(ConfigurationsResponseScanAllPolicy scanAllPolicy) {
    this.scanAllPolicy = scanAllPolicy;
    return this;
  }

   /**
   * Get scanAllPolicy
   * @return scanAllPolicy
  **/
  @ApiModelProperty(value = "")
  public ConfigurationsResponseScanAllPolicy getScanAllPolicy() {
    return scanAllPolicy;
  }

  public void setScanAllPolicy(ConfigurationsResponseScanAllPolicy scanAllPolicy) {
    this.scanAllPolicy = scanAllPolicy;
  }

  public ConfigurationsResponse sessionTimeout(IntegerConfigItem sessionTimeout) {
    this.sessionTimeout = sessionTimeout;
    return this;
  }

   /**
   * The session timeout in minutes
   * @return sessionTimeout
  **/
  @ApiModelProperty(value = "The session timeout in minutes")
  public IntegerConfigItem getSessionTimeout() {
    return sessionTimeout;
  }

  public void setSessionTimeout(IntegerConfigItem sessionTimeout) {
    this.sessionTimeout = sessionTimeout;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigurationsResponse configurationsResponse = (ConfigurationsResponse) o;
    return Objects.equals(this.authMode, configurationsResponse.authMode) &&
        Objects.equals(this.ldapBaseDn, configurationsResponse.ldapBaseDn) &&
        Objects.equals(this.ldapFilter, configurationsResponse.ldapFilter) &&
        Objects.equals(this.ldapGroupBaseDn, configurationsResponse.ldapGroupBaseDn) &&
        Objects.equals(this.ldapGroupAdminDn, configurationsResponse.ldapGroupAdminDn) &&
        Objects.equals(this.ldapGroupAttributeName, configurationsResponse.ldapGroupAttributeName) &&
        Objects.equals(this.ldapGroupSearchFilter, configurationsResponse.ldapGroupSearchFilter) &&
        Objects.equals(this.ldapGroupSearchScope, configurationsResponse.ldapGroupSearchScope) &&
        Objects.equals(this.ldapScope, configurationsResponse.ldapScope) &&
        Objects.equals(this.ldapSearchDn, configurationsResponse.ldapSearchDn) &&
        Objects.equals(this.ldapTimeout, configurationsResponse.ldapTimeout) &&
        Objects.equals(this.ldapUid, configurationsResponse.ldapUid) &&
        Objects.equals(this.ldapUrl, configurationsResponse.ldapUrl) &&
        Objects.equals(this.ldapVerifyCert, configurationsResponse.ldapVerifyCert) &&
        Objects.equals(this.ldapGroupMembershipAttribute, configurationsResponse.ldapGroupMembershipAttribute) &&
        Objects.equals(this.projectCreationRestriction, configurationsResponse.projectCreationRestriction) &&
        Objects.equals(this.readOnly, configurationsResponse.readOnly) &&
        Objects.equals(this.selfRegistration, configurationsResponse.selfRegistration) &&
        Objects.equals(this.tokenExpiration, configurationsResponse.tokenExpiration) &&
        Objects.equals(this.uaaClientId, configurationsResponse.uaaClientId) &&
        Objects.equals(this.uaaClientSecret, configurationsResponse.uaaClientSecret) &&
        Objects.equals(this.uaaEndpoint, configurationsResponse.uaaEndpoint) &&
        Objects.equals(this.uaaVerifyCert, configurationsResponse.uaaVerifyCert) &&
        Objects.equals(this.httpAuthproxyEndpoint, configurationsResponse.httpAuthproxyEndpoint) &&
        Objects.equals(this.httpAuthproxyTokenreviewEndpoint, configurationsResponse.httpAuthproxyTokenreviewEndpoint) &&
        Objects.equals(this.httpAuthproxyAdminGroups, configurationsResponse.httpAuthproxyAdminGroups) &&
        Objects.equals(this.httpAuthproxyAdminUsernames, configurationsResponse.httpAuthproxyAdminUsernames) &&
        Objects.equals(this.httpAuthproxyVerifyCert, configurationsResponse.httpAuthproxyVerifyCert) &&
        Objects.equals(this.httpAuthproxySkipSearch, configurationsResponse.httpAuthproxySkipSearch) &&
        Objects.equals(this.httpAuthproxyServerCertificate, configurationsResponse.httpAuthproxyServerCertificate) &&
        Objects.equals(this.oidcName, configurationsResponse.oidcName) &&
        Objects.equals(this.oidcEndpoint, configurationsResponse.oidcEndpoint) &&
        Objects.equals(this.oidcClientId, configurationsResponse.oidcClientId) &&
        Objects.equals(this.oidcGroupsClaim, configurationsResponse.oidcGroupsClaim) &&
        Objects.equals(this.oidcAdminGroup, configurationsResponse.oidcAdminGroup) &&
        Objects.equals(this.oidcGroupFilter, configurationsResponse.oidcGroupFilter) &&
        Objects.equals(this.oidcScope, configurationsResponse.oidcScope) &&
        Objects.equals(this.oidcUserClaim, configurationsResponse.oidcUserClaim) &&
        Objects.equals(this.oidcVerifyCert, configurationsResponse.oidcVerifyCert) &&
        Objects.equals(this.oidcAutoOnboard, configurationsResponse.oidcAutoOnboard) &&
        Objects.equals(this.oidcExtraRedirectParms, configurationsResponse.oidcExtraRedirectParms) &&
        Objects.equals(this.robotTokenDuration, configurationsResponse.robotTokenDuration) &&
        Objects.equals(this.robotNamePrefix, configurationsResponse.robotNamePrefix) &&
        Objects.equals(this.notificationEnable, configurationsResponse.notificationEnable) &&
        Objects.equals(this.quotaPerProjectEnable, configurationsResponse.quotaPerProjectEnable) &&
        Objects.equals(this.storagePerProject, configurationsResponse.storagePerProject) &&
        Objects.equals(this.auditLogForwardEndpoint, configurationsResponse.auditLogForwardEndpoint) &&
        Objects.equals(this.skipAuditLogDatabase, configurationsResponse.skipAuditLogDatabase) &&
        Objects.equals(this.scanAllPolicy, configurationsResponse.scanAllPolicy) &&
        Objects.equals(this.sessionTimeout, configurationsResponse.sessionTimeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authMode, ldapBaseDn, ldapFilter, ldapGroupBaseDn, ldapGroupAdminDn, ldapGroupAttributeName, ldapGroupSearchFilter, ldapGroupSearchScope, ldapScope, ldapSearchDn, ldapTimeout, ldapUid, ldapUrl, ldapVerifyCert, ldapGroupMembershipAttribute, projectCreationRestriction, readOnly, selfRegistration, tokenExpiration, uaaClientId, uaaClientSecret, uaaEndpoint, uaaVerifyCert, httpAuthproxyEndpoint, httpAuthproxyTokenreviewEndpoint, httpAuthproxyAdminGroups, httpAuthproxyAdminUsernames, httpAuthproxyVerifyCert, httpAuthproxySkipSearch, httpAuthproxyServerCertificate, oidcName, oidcEndpoint, oidcClientId, oidcGroupsClaim, oidcAdminGroup, oidcGroupFilter, oidcScope, oidcUserClaim, oidcVerifyCert, oidcAutoOnboard, oidcExtraRedirectParms, robotTokenDuration, robotNamePrefix, notificationEnable, quotaPerProjectEnable, storagePerProject, auditLogForwardEndpoint, skipAuditLogDatabase, scanAllPolicy, sessionTimeout);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigurationsResponse {\n");
    
    sb.append("    authMode: ").append(toIndentedString(authMode)).append("\n");
    sb.append("    ldapBaseDn: ").append(toIndentedString(ldapBaseDn)).append("\n");
    sb.append("    ldapFilter: ").append(toIndentedString(ldapFilter)).append("\n");
    sb.append("    ldapGroupBaseDn: ").append(toIndentedString(ldapGroupBaseDn)).append("\n");
    sb.append("    ldapGroupAdminDn: ").append(toIndentedString(ldapGroupAdminDn)).append("\n");
    sb.append("    ldapGroupAttributeName: ").append(toIndentedString(ldapGroupAttributeName)).append("\n");
    sb.append("    ldapGroupSearchFilter: ").append(toIndentedString(ldapGroupSearchFilter)).append("\n");
    sb.append("    ldapGroupSearchScope: ").append(toIndentedString(ldapGroupSearchScope)).append("\n");
    sb.append("    ldapScope: ").append(toIndentedString(ldapScope)).append("\n");
    sb.append("    ldapSearchDn: ").append(toIndentedString(ldapSearchDn)).append("\n");
    sb.append("    ldapTimeout: ").append(toIndentedString(ldapTimeout)).append("\n");
    sb.append("    ldapUid: ").append(toIndentedString(ldapUid)).append("\n");
    sb.append("    ldapUrl: ").append(toIndentedString(ldapUrl)).append("\n");
    sb.append("    ldapVerifyCert: ").append(toIndentedString(ldapVerifyCert)).append("\n");
    sb.append("    ldapGroupMembershipAttribute: ").append(toIndentedString(ldapGroupMembershipAttribute)).append("\n");
    sb.append("    projectCreationRestriction: ").append(toIndentedString(projectCreationRestriction)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    selfRegistration: ").append(toIndentedString(selfRegistration)).append("\n");
    sb.append("    tokenExpiration: ").append(toIndentedString(tokenExpiration)).append("\n");
    sb.append("    uaaClientId: ").append(toIndentedString(uaaClientId)).append("\n");
    sb.append("    uaaClientSecret: ").append(toIndentedString(uaaClientSecret)).append("\n");
    sb.append("    uaaEndpoint: ").append(toIndentedString(uaaEndpoint)).append("\n");
    sb.append("    uaaVerifyCert: ").append(toIndentedString(uaaVerifyCert)).append("\n");
    sb.append("    httpAuthproxyEndpoint: ").append(toIndentedString(httpAuthproxyEndpoint)).append("\n");
    sb.append("    httpAuthproxyTokenreviewEndpoint: ").append(toIndentedString(httpAuthproxyTokenreviewEndpoint)).append("\n");
    sb.append("    httpAuthproxyAdminGroups: ").append(toIndentedString(httpAuthproxyAdminGroups)).append("\n");
    sb.append("    httpAuthproxyAdminUsernames: ").append(toIndentedString(httpAuthproxyAdminUsernames)).append("\n");
    sb.append("    httpAuthproxyVerifyCert: ").append(toIndentedString(httpAuthproxyVerifyCert)).append("\n");
    sb.append("    httpAuthproxySkipSearch: ").append(toIndentedString(httpAuthproxySkipSearch)).append("\n");
    sb.append("    httpAuthproxyServerCertificate: ").append(toIndentedString(httpAuthproxyServerCertificate)).append("\n");
    sb.append("    oidcName: ").append(toIndentedString(oidcName)).append("\n");
    sb.append("    oidcEndpoint: ").append(toIndentedString(oidcEndpoint)).append("\n");
    sb.append("    oidcClientId: ").append(toIndentedString(oidcClientId)).append("\n");
    sb.append("    oidcGroupsClaim: ").append(toIndentedString(oidcGroupsClaim)).append("\n");
    sb.append("    oidcAdminGroup: ").append(toIndentedString(oidcAdminGroup)).append("\n");
    sb.append("    oidcGroupFilter: ").append(toIndentedString(oidcGroupFilter)).append("\n");
    sb.append("    oidcScope: ").append(toIndentedString(oidcScope)).append("\n");
    sb.append("    oidcUserClaim: ").append(toIndentedString(oidcUserClaim)).append("\n");
    sb.append("    oidcVerifyCert: ").append(toIndentedString(oidcVerifyCert)).append("\n");
    sb.append("    oidcAutoOnboard: ").append(toIndentedString(oidcAutoOnboard)).append("\n");
    sb.append("    oidcExtraRedirectParms: ").append(toIndentedString(oidcExtraRedirectParms)).append("\n");
    sb.append("    robotTokenDuration: ").append(toIndentedString(robotTokenDuration)).append("\n");
    sb.append("    robotNamePrefix: ").append(toIndentedString(robotNamePrefix)).append("\n");
    sb.append("    notificationEnable: ").append(toIndentedString(notificationEnable)).append("\n");
    sb.append("    quotaPerProjectEnable: ").append(toIndentedString(quotaPerProjectEnable)).append("\n");
    sb.append("    storagePerProject: ").append(toIndentedString(storagePerProject)).append("\n");
    sb.append("    auditLogForwardEndpoint: ").append(toIndentedString(auditLogForwardEndpoint)).append("\n");
    sb.append("    skipAuditLogDatabase: ").append(toIndentedString(skipAuditLogDatabase)).append("\n");
    sb.append("    scanAllPolicy: ").append(toIndentedString(scanAllPolicy)).append("\n");
    sb.append("    sessionTimeout: ").append(toIndentedString(sessionTimeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

