/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The ldap ping result
 */
@ApiModel(description = "The ldap ping result")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class LdapPingResult {
  @SerializedName("success")
  private Boolean success = null;

  @SerializedName("message")
  private String message = null;

  public LdapPingResult success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * Test success
   * @return success
  **/
  @ApiModelProperty(value = "Test success")
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public LdapPingResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * The ping operation output message.
   * @return message
  **/
  @ApiModelProperty(value = "The ping operation output message.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LdapPingResult ldapPingResult = (LdapPingResult) o;
    return Objects.equals(this.success, ldapPingResult.success) &&
        Objects.equals(this.message, ldapPingResult.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LdapPingResult {\n");
    
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

