/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * LdapImportUsers
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class LdapImportUsers {
  @SerializedName("ldap_uid_list")
  private List<String> ldapUidList = null;

  public LdapImportUsers ldapUidList(List<String> ldapUidList) {
    this.ldapUidList = ldapUidList;
    return this;
  }

  public LdapImportUsers addLdapUidListItem(String ldapUidListItem) {
    if (this.ldapUidList == null) {
      this.ldapUidList = new ArrayList<String>();
    }
    this.ldapUidList.add(ldapUidListItem);
    return this;
  }

   /**
   * selected uid list
   * @return ldapUidList
  **/
  @ApiModelProperty(value = "selected uid list")
  public List<String> getLdapUidList() {
    return ldapUidList;
  }

  public void setLdapUidList(List<String> ldapUidList) {
    this.ldapUidList = ldapUidList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LdapImportUsers ldapImportUsers = (LdapImportUsers) o;
    return Objects.equals(this.ldapUidList, ldapImportUsers.ldapUidList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ldapUidList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LdapImportUsers {\n");
    
    sb.append("    ldapUidList: ").append(toIndentedString(ldapUidList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

