/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ProjectReq
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class ProjectReq {
  @SerializedName("project_name")
  private String projectName = null;

  @SerializedName("public")
  private Boolean _public = null;

  @SerializedName("metadata")
  private ProjectMetadata metadata = null;

  @SerializedName("cve_allowlist")
  private CVEAllowlist cveAllowlist = null;

  @SerializedName("storage_limit")
  private Long storageLimit = null;

  @SerializedName("registry_id")
  private Long registryId = null;

  public ProjectReq projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * The name of the project.
   * @return projectName
  **/
  @ApiModelProperty(value = "The name of the project.")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public ProjectReq _public(Boolean _public) {
    this._public = _public;
    return this;
  }

   /**
   * deprecated, reserved for project creation in replication
   * @return _public
  **/
  @ApiModelProperty(value = "deprecated, reserved for project creation in replication")
  public Boolean isPublic() {
    return _public;
  }

  public void setPublic(Boolean _public) {
    this._public = _public;
  }

  public ProjectReq metadata(ProjectMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * The metadata of the project.
   * @return metadata
  **/
  @ApiModelProperty(value = "The metadata of the project.")
  public ProjectMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(ProjectMetadata metadata) {
    this.metadata = metadata;
  }

  public ProjectReq cveAllowlist(CVEAllowlist cveAllowlist) {
    this.cveAllowlist = cveAllowlist;
    return this;
  }

   /**
   * The CVE allowlist of the project.
   * @return cveAllowlist
  **/
  @ApiModelProperty(value = "The CVE allowlist of the project.")
  public CVEAllowlist getCveAllowlist() {
    return cveAllowlist;
  }

  public void setCveAllowlist(CVEAllowlist cveAllowlist) {
    this.cveAllowlist = cveAllowlist;
  }

  public ProjectReq storageLimit(Long storageLimit) {
    this.storageLimit = storageLimit;
    return this;
  }

   /**
   * The storage quota of the project.
   * @return storageLimit
  **/
  @ApiModelProperty(value = "The storage quota of the project.")
  public Long getStorageLimit() {
    return storageLimit;
  }

  public void setStorageLimit(Long storageLimit) {
    this.storageLimit = storageLimit;
  }

  public ProjectReq registryId(Long registryId) {
    this.registryId = registryId;
    return this;
  }

   /**
   * The ID of referenced registry when creating the proxy cache project
   * @return registryId
  **/
  @ApiModelProperty(value = "The ID of referenced registry when creating the proxy cache project")
  public Long getRegistryId() {
    return registryId;
  }

  public void setRegistryId(Long registryId) {
    this.registryId = registryId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectReq projectReq = (ProjectReq) o;
    return Objects.equals(this.projectName, projectReq.projectName) &&
        Objects.equals(this._public, projectReq._public) &&
        Objects.equals(this.metadata, projectReq.metadata) &&
        Objects.equals(this.cveAllowlist, projectReq.cveAllowlist) &&
        Objects.equals(this.storageLimit, projectReq.storageLimit) &&
        Objects.equals(this.registryId, projectReq.registryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectName, _public, metadata, cveAllowlist, storageLimit, registryId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectReq {\n");
    
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    cveAllowlist: ").append(toIndentedString(cveAllowlist)).append("\n");
    sb.append("    storageLimit: ").append(toIndentedString(storageLimit)).append("\n");
    sb.append("    registryId: ").append(toIndentedString(registryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

