/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * RegistryUpdate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class RegistryUpdate {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("credential_type")
  private String credentialType = null;

  @SerializedName("access_key")
  private String accessKey = null;

  @SerializedName("access_secret")
  private String accessSecret = null;

  @SerializedName("insecure")
  private Boolean insecure = null;

  public RegistryUpdate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The registry name.
   * @return name
  **/
  @ApiModelProperty(value = "The registry name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RegistryUpdate description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the registry.
   * @return description
  **/
  @ApiModelProperty(value = "Description of the registry.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RegistryUpdate url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The registry URL.
   * @return url
  **/
  @ApiModelProperty(value = "The registry URL.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public RegistryUpdate credentialType(String credentialType) {
    this.credentialType = credentialType;
    return this;
  }

   /**
   * Credential type of the registry, e.g. &#39;basic&#39;.
   * @return credentialType
  **/
  @ApiModelProperty(value = "Credential type of the registry, e.g. 'basic'.")
  public String getCredentialType() {
    return credentialType;
  }

  public void setCredentialType(String credentialType) {
    this.credentialType = credentialType;
  }

  public RegistryUpdate accessKey(String accessKey) {
    this.accessKey = accessKey;
    return this;
  }

   /**
   * The registry access key.
   * @return accessKey
  **/
  @ApiModelProperty(value = "The registry access key.")
  public String getAccessKey() {
    return accessKey;
  }

  public void setAccessKey(String accessKey) {
    this.accessKey = accessKey;
  }

  public RegistryUpdate accessSecret(String accessSecret) {
    this.accessSecret = accessSecret;
    return this;
  }

   /**
   * The registry access secret.
   * @return accessSecret
  **/
  @ApiModelProperty(value = "The registry access secret.")
  public String getAccessSecret() {
    return accessSecret;
  }

  public void setAccessSecret(String accessSecret) {
    this.accessSecret = accessSecret;
  }

  public RegistryUpdate insecure(Boolean insecure) {
    this.insecure = insecure;
    return this;
  }

   /**
   * Whether or not the certificate will be verified when Harbor tries to access the server.
   * @return insecure
  **/
  @ApiModelProperty(value = "Whether or not the certificate will be verified when Harbor tries to access the server.")
  public Boolean isInsecure() {
    return insecure;
  }

  public void setInsecure(Boolean insecure) {
    this.insecure = insecure;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistryUpdate registryUpdate = (RegistryUpdate) o;
    return Objects.equals(this.name, registryUpdate.name) &&
        Objects.equals(this.description, registryUpdate.description) &&
        Objects.equals(this.url, registryUpdate.url) &&
        Objects.equals(this.credentialType, registryUpdate.credentialType) &&
        Objects.equals(this.accessKey, registryUpdate.accessKey) &&
        Objects.equals(this.accessSecret, registryUpdate.accessSecret) &&
        Objects.equals(this.insecure, registryUpdate.insecure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, url, credentialType, accessKey, accessSecret, insecure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistryUpdate {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    credentialType: ").append(toIndentedString(credentialType)).append("\n");
    sb.append("    accessKey: ").append(toIndentedString(accessKey)).append("\n");
    sb.append("    accessSecret: ").append(toIndentedString(accessSecret)).append("\n");
    sb.append("    insecure: ").append(toIndentedString(insecure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

