/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Scanner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class Scanner {
  @SerializedName("name")
  private String name = null;

  @SerializedName("vendor")
  private String vendor = null;

  @SerializedName("version")
  private String version = null;

  public Scanner name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the scanner
   * @return name
  **/
  @ApiModelProperty(example = "Trivy", value = "Name of the scanner")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Scanner vendor(String vendor) {
    this.vendor = vendor;
    return this;
  }

   /**
   * Name of the scanner provider
   * @return vendor
  **/
  @ApiModelProperty(example = "Aqua Security", value = "Name of the scanner provider")
  public String getVendor() {
    return vendor;
  }

  public void setVendor(String vendor) {
    this.vendor = vendor;
  }

  public Scanner version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Version of the scanner adapter
   * @return version
  **/
  @ApiModelProperty(example = "v0.9.1", value = "Version of the scanner adapter")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Scanner scanner = (Scanner) o;
    return Objects.equals(this.name, scanner.name) &&
        Objects.equals(this.vendor, scanner.vendor) &&
        Objects.equals(this.version, scanner.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, vendor, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Scanner {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

