/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * the schedule task info
 */
@ApiModel(description = "the schedule task info")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class ScheduleTask {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("vendor_type")
  private String vendorType = null;

  @SerializedName("vendor_id")
  private Integer vendorId = null;

  @SerializedName("cron")
  private String cron = null;

  @SerializedName("update_time")
  private String updateTime = null;

  public ScheduleTask id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * the id of the Schedule task
   * @return id
  **/
  @ApiModelProperty(value = "the id of the Schedule task")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ScheduleTask vendorType(String vendorType) {
    this.vendorType = vendorType;
    return this;
  }

   /**
   * the vendor type of the current schedule task
   * @return vendorType
  **/
  @ApiModelProperty(value = "the vendor type of the current schedule task")
  public String getVendorType() {
    return vendorType;
  }

  public void setVendorType(String vendorType) {
    this.vendorType = vendorType;
  }

  public ScheduleTask vendorId(Integer vendorId) {
    this.vendorId = vendorId;
    return this;
  }

   /**
   * the vendor id of the current task
   * @return vendorId
  **/
  @ApiModelProperty(value = "the vendor id of the current task")
  public Integer getVendorId() {
    return vendorId;
  }

  public void setVendorId(Integer vendorId) {
    this.vendorId = vendorId;
  }

  public ScheduleTask cron(String cron) {
    this.cron = cron;
    return this;
  }

   /**
   * the cron of the current schedule task
   * @return cron
  **/
  @ApiModelProperty(value = "the cron of the current schedule task")
  public String getCron() {
    return cron;
  }

  public void setCron(String cron) {
    this.cron = cron;
  }

  public ScheduleTask updateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * the update time of the schedule task
   * @return updateTime
  **/
  @ApiModelProperty(value = "the update time of the schedule task")
  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleTask scheduleTask = (ScheduleTask) o;
    return Objects.equals(this.id, scheduleTask.id) &&
        Objects.equals(this.vendorType, scheduleTask.vendorType) &&
        Objects.equals(this.vendorId, scheduleTask.vendorId) &&
        Objects.equals(this.cron, scheduleTask.cron) &&
        Objects.equals(this.updateTime, scheduleTask.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, vendorType, vendorId, cron, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleTask {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    vendorType: ").append(toIndentedString(vendorType)).append("\n");
    sb.append("    vendorId: ").append(toIndentedString(vendorId)).append("\n");
    sb.append("    cron: ").append(toIndentedString(cron)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

