/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * UserResp
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class UserResp {
  @SerializedName("email")
  private String email = null;

  @SerializedName("realname")
  private String realname = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("user_id")
  private Integer userId = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("sysadmin_flag")
  private Boolean sysadminFlag = null;

  @SerializedName("admin_role_in_auth")
  private Boolean adminRoleInAuth = null;

  @SerializedName("oidc_user_meta")
  private OIDCUserInfo oidcUserMeta = null;

  @SerializedName("creation_time")
  private String creationTime = null;

  @SerializedName("update_time")
  private String updateTime = null;

  public UserResp email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserResp realname(String realname) {
    this.realname = realname;
    return this;
  }

   /**
   * Get realname
   * @return realname
  **/
  @ApiModelProperty(value = "")
  public String getRealname() {
    return realname;
  }

  public void setRealname(String realname) {
    this.realname = realname;
  }

  public UserResp comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public UserResp userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public UserResp username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public UserResp sysadminFlag(Boolean sysadminFlag) {
    this.sysadminFlag = sysadminFlag;
    return this;
  }

   /**
   * Get sysadminFlag
   * @return sysadminFlag
  **/
  @ApiModelProperty(value = "")
  public Boolean isSysadminFlag() {
    return sysadminFlag;
  }

  public void setSysadminFlag(Boolean sysadminFlag) {
    this.sysadminFlag = sysadminFlag;
  }

  public UserResp adminRoleInAuth(Boolean adminRoleInAuth) {
    this.adminRoleInAuth = adminRoleInAuth;
    return this;
  }

   /**
   * indicate the admin privilege is grant by authenticator (LDAP), is always false unless it is the current login user
   * @return adminRoleInAuth
  **/
  @ApiModelProperty(value = "indicate the admin privilege is grant by authenticator (LDAP), is always false unless it is the current login user")
  public Boolean isAdminRoleInAuth() {
    return adminRoleInAuth;
  }

  public void setAdminRoleInAuth(Boolean adminRoleInAuth) {
    this.adminRoleInAuth = adminRoleInAuth;
  }

  public UserResp oidcUserMeta(OIDCUserInfo oidcUserMeta) {
    this.oidcUserMeta = oidcUserMeta;
    return this;
  }

   /**
   * Get oidcUserMeta
   * @return oidcUserMeta
  **/
  @ApiModelProperty(value = "")
  public OIDCUserInfo getOidcUserMeta() {
    return oidcUserMeta;
  }

  public void setOidcUserMeta(OIDCUserInfo oidcUserMeta) {
    this.oidcUserMeta = oidcUserMeta;
  }

  public UserResp creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * The creation time of the user.
   * @return creationTime
  **/
  @ApiModelProperty(value = "The creation time of the user.")
  public String getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }

  public UserResp updateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * The update time of the user.
   * @return updateTime
  **/
  @ApiModelProperty(value = "The update time of the user.")
  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserResp userResp = (UserResp) o;
    return Objects.equals(this.email, userResp.email) &&
        Objects.equals(this.realname, userResp.realname) &&
        Objects.equals(this.comment, userResp.comment) &&
        Objects.equals(this.userId, userResp.userId) &&
        Objects.equals(this.username, userResp.username) &&
        Objects.equals(this.sysadminFlag, userResp.sysadminFlag) &&
        Objects.equals(this.adminRoleInAuth, userResp.adminRoleInAuth) &&
        Objects.equals(this.oidcUserMeta, userResp.oidcUserMeta) &&
        Objects.equals(this.creationTime, userResp.creationTime) &&
        Objects.equals(this.updateTime, userResp.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, realname, comment, userId, username, sysadminFlag, adminRoleInAuth, oidcUserMeta, creationTime, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserResp {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    realname: ").append(toIndentedString(realname)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    sysadminFlag: ").append(toIndentedString(sysadminFlag)).append("\n");
    sb.append("    adminRoleInAuth: ").append(toIndentedString(adminRoleInAuth)).append("\n");
    sb.append("    oidcUserMeta: ").append(toIndentedString(oidcUserMeta)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

