/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.codeonline.cloud.harbor.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * worker in the pool
 */
@ApiModel(description = "worker in the pool")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-30T20:20:43.840Z")
public class Worker {
  @SerializedName("id")
  private String id = null;

  @SerializedName("pool_id")
  private String poolId = null;

  @SerializedName("job_name")
  private String jobName = null;

  @SerializedName("job_id")
  private String jobId = null;

  @SerializedName("start_at")
  private String startAt = null;

  @SerializedName("check_in")
  private String checkIn = null;

  @SerializedName("checkin_at")
  private String checkinAt = null;

  public Worker id(String id) {
    this.id = id;
    return this;
  }

   /**
   * the id of the worker
   * @return id
  **/
  @ApiModelProperty(value = "the id of the worker")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Worker poolId(String poolId) {
    this.poolId = poolId;
    return this;
  }

   /**
   * the id of the worker pool
   * @return poolId
  **/
  @ApiModelProperty(value = "the id of the worker pool")
  public String getPoolId() {
    return poolId;
  }

  public void setPoolId(String poolId) {
    this.poolId = poolId;
  }

  public Worker jobName(String jobName) {
    this.jobName = jobName;
    return this;
  }

   /**
   * the name of the running job in the worker
   * @return jobName
  **/
  @ApiModelProperty(value = "the name of the running job in the worker")
  public String getJobName() {
    return jobName;
  }

  public void setJobName(String jobName) {
    this.jobName = jobName;
  }

  public Worker jobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * the id of the running job in the worker
   * @return jobId
  **/
  @ApiModelProperty(value = "the id of the running job in the worker")
  public String getJobId() {
    return jobId;
  }

  public void setJobId(String jobId) {
    this.jobId = jobId;
  }

  public Worker startAt(String startAt) {
    this.startAt = startAt;
    return this;
  }

   /**
   * The start time of the worker
   * @return startAt
  **/
  @ApiModelProperty(value = "The start time of the worker")
  public String getStartAt() {
    return startAt;
  }

  public void setStartAt(String startAt) {
    this.startAt = startAt;
  }

  public Worker checkIn(String checkIn) {
    this.checkIn = checkIn;
    return this;
  }

   /**
   * the checkin of the running job in the worker
   * @return checkIn
  **/
  @ApiModelProperty(value = "the checkin of the running job in the worker")
  public String getCheckIn() {
    return checkIn;
  }

  public void setCheckIn(String checkIn) {
    this.checkIn = checkIn;
  }

  public Worker checkinAt(String checkinAt) {
    this.checkinAt = checkinAt;
    return this;
  }

   /**
   * The checkin time of the worker
   * @return checkinAt
  **/
  @ApiModelProperty(value = "The checkin time of the worker")
  public String getCheckinAt() {
    return checkinAt;
  }

  public void setCheckinAt(String checkinAt) {
    this.checkinAt = checkinAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Worker worker = (Worker) o;
    return Objects.equals(this.id, worker.id) &&
        Objects.equals(this.poolId, worker.poolId) &&
        Objects.equals(this.jobName, worker.jobName) &&
        Objects.equals(this.jobId, worker.jobId) &&
        Objects.equals(this.startAt, worker.startAt) &&
        Objects.equals(this.checkIn, worker.checkIn) &&
        Objects.equals(this.checkinAt, worker.checkinAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, poolId, jobName, jobId, startAt, checkIn, checkinAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Worker {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    poolId: ").append(toIndentedString(poolId)).append("\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    startAt: ").append(toIndentedString(startAt)).append("\n");
    sb.append("    checkIn: ").append(toIndentedString(checkIn)).append("\n");
    sb.append("    checkinAt: ").append(toIndentedString(checkinAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

