# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER codeonline

# 挂载目录
VOLUME /home/codeonline
# 创建目录
RUN mkdir -p /home/codeonline
# 指定路径
WORKDIR /home/codeonline
# 复制jar文件到路径
COPY ./jar/codeonline-visual-monitor.jar /home/codeonline/codeonline-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","codeonline-visual-monitor.jar"]
